# Generated by Django 5.2.6 on 2026-05-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('supplier', models.CharField(max_length=120)),
                ('quantity_liters', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_liters', models.PositiveIntegerField()),
                ('destination', models.CharField(max_length=150)),
                ('issued_at', models.DateTimeField()),
                ('fuel_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fuelitem')),
            ],
        ),
    ]
