# Generated by Django 5.2.6 on 2026-05-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('hashed_password', models.CharField(max_length=128)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
    ]
